import React from "react";

import StyledComponentsRegistry from "@/app/lib/AntdRegistry";


export const metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

const RootLayout = async ({ children }: React.PropsWithChildren) => (
    <main>
      <StyledComponentsRegistry>
        {children}</StyledComponentsRegistry>
    </main>
);

export default RootLayout;
